### ISSUE TITLE
status-added color question

### ISSUE THREAD

**Issue by zephraph** [atom/one-dark-syntax#12]
Why is the status-added class shown in the status bar blue? I would assume it would be the same as text-color-added which maps to text-color-success which is green in my case.

![color](https://cloud.githubusercontent.com/assets/3087225/5970932/842f45b4-a800-11e4-860a-88eff88953fc.png)

Is this intentional because blue is easier on the eyes?

**Comment by simurai** [comment]
@zephraph Hmm.. good point. Not sure if it was intentional. Anyways, I agree, it's inconsistent like that. Will be fixed in the next release of the Atom and One themes.
