### ISSUE TITLE
Screenshot doesn't match colors.

### ISSUE THREAD

**Issue by francoiscote** [atom/one-dark-syntax#14]
Are these the new colors of this syntax theme ?

![screen shot 2015-02-12 at 20 36 22](https://cloud.githubusercontent.com/assets/116375/6180720/f92367be-b2f6-11e4-8fb4-dac92d56bfae.png)

If yes, the repo would need an updated screenshot.
If not, I have something wrong with my setup.

**Comment by simurai** [comment]
@francoiscote Yes, there were some recent changes. Increase saturation for certain colors. Most noticeable on the `atom-text-editor`.

Current screenshot:

![one-syntax-dark](https://cloud.githubusercontent.com/assets/378023/5795461/f8d0deda-9fd3-11e4-94d3-be982bd83edd.png)

Actual colors:

![one-syntax-dark](https://cloud.githubusercontent.com/assets/378023/6182125/1e2c65c6-b381-11e4-9dd8-a39d53c32d37.png)

I'll update the screenshot.
