### ISSUE TITLE
Font Family specification

### ISSUE THREAD

**Issue by PabloVallejo** [atom/one-dark-syntax#16]
I've installed the package and I'm using the default Atom font family which looks a little different. Can you tell me which family is the one used in the screenshots. 

Thanks a lot

**Comment by simurai** [comment]
@PabloVallejo It's `Fira Mono`. You can download it here: https://github.com/mozilla/Fira

**Note to self**: Use the default font-family when taking screenshots next time. :innocent:

**Comment by PabloVallejo** [comment]
Thanks :+1:
