### ISSUE TITLE
CSS properties

### ISSUE THREAD

**Issue by sryze** [atom/one-dark-syntax#24]
It would be nice if this theme highlighted valid CSS property names like in e.g. Atom Dark.

**Comment by simurai** [comment]
Do you mind adding an example?

**Comment by sryze** [comment]
OK, here is One Dark - all properties are colored as default text:

![atom-css-syntax-bad](https://cloud.githubusercontent.com/assets/4525736/7176419/086db45c-e440-11e4-98aa-fdc1dd75694f.png)

and this is Atom Light, valid properties are kind of bold-ish:

![atom-css-syntax-good](https://cloud.githubusercontent.com/assets/4525736/7176445/4da493ba-e440-11e4-9df5-d5cf69b1cefe.png)

**Comment by simurai** [comment]
Thanks. Ok, I see. Yeah, the color should be different if it's a valid property name.

**Comment by simurai** [comment]
Invalid properties/values will be toned down a bit.

![screen shot 2015-05-22 at 12 53 16 pm](https://cloud.githubusercontent.com/assets/378023/7763806/95093df2-0081-11e5-9e76-a5af281971ba.png)

At the same time also the punctuation, but that's arguably a good thing. Colors will probably change too: https://github.com/atom/one-dark-syntax/pull/30
