### ISSUE TITLE
Add coloring for `support.type` scope (found in python)

### ISSUE THREAD

**Issue by mehcode** [atom/one-dark-syntax#36]
![screenshot from 2015-06-03 21 58 01](https://cloud.githubusercontent.com/assets/753919/7977118/a6a65946-0a3b-11e5-9e17-1eaa41d22872.png)
> One Dark

![screenshot from 2015-06-03 21 58 13](https://cloud.githubusercontent.com/assets/753919/7977120/a82879d4-0a3b-11e5-9b74-55e9719a58ec.png)
> Atom Dark

**Comment by simurai** [comment]
@mehcode By `support.type`, do you mean the `int` in your example?

If so, it seems that coloring got added through the `.support.function` scope:

![screen shot 2015-07-16 at 6 08 07 pm](https://cloud.githubusercontent.com/assets/378023/8719308/abe591b2-2be5-11e5-8b7a-9add819d905c.png)

**Comment by mehcode** [comment]
I could have sworn that language-python identified `int` as `.support.type`. It now works for python, which is awesome but that was just a case I was using to show an example. I would still like coloring for `.support` or `.support.type`. Atom Dark has a color specified for `.support.type`.

**Comment by simurai** [comment]
> Atom Dark has a color specified for .support.type.

Do you mean [here](https://github.com/atom/atom-dark-syntax/blob/master/index.less#L226)

```less
.support {
  &.type.property-name.css {
    color: #EDEDED;
  }
}
```

Seems to target CSS property names that are supported:

![screen shot 2015-07-17 at 2 52 07 pm](https://cloud.githubusercontent.com/assets/378023/8741444/c267d9b4-2c93-11e5-9d3d-876b193a4ef8.png)

In One dark that gets styled with [this](https://github.com/atom/one-dark-syntax/blob/master/styles/languages/css.less#L7).

**Comment by mehcode** [comment]
I mean [here](https://github.com/atom/atom-dark-syntax/blob/master/index.less#L216) apparently. I've been writing a syntax package and used `.support.type` to indicate a built-in type and was confused when `atom-dark` seemed to highlight it but `one-dark` did not.

```
.support {
  color: #FFFFB6;
}
```

**Comment by simurai** [comment]
I see.. ok, made a PR #41 for `.support.type` with the same color as functions.

btw. this recent PR https://github.com/atom/language-python/pull/72 is probably the reason `int` changed from `.support.type` to `.support.function`.

**Comment by mehcode** [comment]
Thank you @simurai
