### ISSUE TITLE
Failed to activate the retro-gruvbox theme

### ISSUE THREAD

**Issue by Nanaotakashi** [atom/one-dark-syntax#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [one-dark-syntax](https://github.com/atom/one-dark-syntax) package, v0.7.1

### Stack Trace

Failed to activate the retro-gruvbox theme

```
At variable @mono-3 is undefined in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-syntax/styles/language.less:2:9

LessError: variable @mono-3 is undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-syntax/styles/language.less:2:9
```

### Commands

```
     -0:34.7.0 settings-view:install-packages-and-themes (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autocomplete-php, v0.3.6
autocomplete-python, v0.4.3
autocomplete-ruby, v0.1.0
color-picker, v2.0.7
language-htaccess, v0.1.1
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @Nanaotakashi -- are you able to reliably reproduce this? I just tried installing and switching to the retro-gruvbox theme and wasn't able to trigger this problem.

@kevinsawicki wondering if you have :bulb: about what happened here. The error message says "Failed to activate the retro-gruvbox theme", but the stack trace mentions only the one-dark-syntax theme. :confused:

**Comment by simurai** [comment]
I can't reproduce it either.

> At variable @mono-3 is undefined

I think `@mono-3` is color variable that gets used for comments. So *maybe* package used that color and then when switching to another theme, that color is not available and it complains? But that's just a wild guess.

@Nanaotakashi What if you reload Atom after you active the retro-gruvbox theme, do you still see the error?

**Comment by Nanaotakashi** [comment]
@simurai It works after I reinstalled it after I uninstalled & restarted my Macbook. 
Thanks @izuzak & @simurai
