### ISSUE TITLE
Someone finally made the perfect UI for Atom

### ISSUE THREAD

**Issue by jdsimcoe** [atom/one-dark-syntax#4]
Thank you, thank you, THANK YOU!!! :+1: :+1: :+1:

**Comment by simurai** [comment]
@jdsimcoe I hope this is not a "real issue". :wink:

I'll close this with a big thanks. :bow:

**Comment by jdsimcoe** [comment]
No, these were not real "issues"... just wanted to say thank you. It was me who forked the default Atom syntax (not your new syntax) and ported it to match one-dark and published. But seeing the comments on discuss.atom.io I decided to remove it until your theme + syntax are officially released. Was not trying to take your work public but wanted a matching syntax.

Sorry for the kerfuffle!

**Comment by simurai** [comment]
@jdsimcoe No worries. If you changed it a bit and it's not a 1:1 copy, feel free to publish it. That's what the themes are for. And maybe pick a new name (to avoid confusion). Although not even sure if "One" will be the final name.
