### ISSUE TITLE
Move specs to its own repo

### ISSUE THREAD

**Issue by simurai** [atom/one-dark-syntax#45]
Currently there are a few "specs" under `atom/one-dark-syntax/spec`.

But it would be better to have them in a separate repo. Then all theme authors could use them and it's not tied to this One. Also, easier to update them in just a single place. And we could reference them from the docs.

I made a new repo here: https://github.com/simurai/language-examples. It contains examples for all the core languages.

@atom/feedback if this is a good idea, could somebody create a new repo for it, maybe `atom/language-examples`?

**Comment by benogle** [comment]
Good idea :+1:

**Comment by kevinsawicki** [comment]
Yeah, if you want we can move your repo into the atom org so all maintainers can merge PRs for it.

**Comment by simurai** [comment]
> Yeah, if you want we can move your repo into the atom org so all maintainers can merge PRs for it.

Sounds good. I tried to transfer it, but it says: "You don’t have admin rights to atom." If you don't mind grabbing the files, keeping the Git history isn't that important.

**Comment by simurai** [comment]
I moved it to the `atom-community` org for now: https://github.com/atom-community/language-examples

I think it's a fitting :house: as well.
