### ISSUE TITLE
what's wrong with colors?

### ISSUE THREAD

**Issue by barwinco** [atom/one-dark-syntax#5]
I have other editor colors than in the repo screenshots, both light and dark theme, what's wrong with colors?

![untitled](https://cloud.githubusercontent.com/assets/2276316/5792156/dad81a4a-9f12-11e4-9ed3-1c09a591e7bc.jpg)

atom-0.175.0-696c795 (Linux)

**Comment by simurai** [comment]
@barwinco That was still an old screenshot, it's now updated. Thanks.

Actually, if you prefer the colors from the old one, they still can be found here: https://github.com/simurai/tone-dark-syntax Not sure if/when that theme will actually be published, but you can install it manuallly.
