### ISSUE TITLE
Markdown with mixed HTML can produce incorrect styling

### ISSUE THREAD

**Issue by SmilinBrian** [atom/one-dark-syntax#51]
I sometimes use `<a href="blah" target="_blank">` HTML tags in my Markdown code when "open the link in a new browser" behavior is appropriate.

Unfortunately the underscore character with in "_blank" triggers the syntax to try to show "Markdown italicized" formatting until a "closing" underscore is encountered somewhere else.

See attached image.

![onedarkunderscore](https://cloud.githubusercontent.com/assets/139918/10557169/e6ce7772-7455-11e5-9659-ba9325c37049.png)

**Comment by simurai** [comment]
This seems to be a duplicate of https://github.com/atom/language-gfm/issues/44.

I'll close this here, but feel free to add a comment there.

**Comment by SmilinBrian** [comment]
Agreed, thanks.
