### ISSUE TITLE
add syntax highlighting support Flow type annotations

### ISSUE THREAD

**Issue by UnsungHero97** [atom/one-dark-syntax#53]
Syntax highlighting for TypeScript works really well, but it does not work in the case where I'm writing JavaScript with [Flow type annotations](http://flowtype.org/).

Flow:
![screen shot 2015-11-02 at 11 37 04 am](https://cloud.githubusercontent.com/assets/440299/10892031/2f060d54-8156-11e5-988d-9b68ecf271b0.png)

TypeScript:
![screen shot 2015-11-02 at 11 36 51 am](https://cloud.githubusercontent.com/assets/440299/10892040/360127d8-8156-11e5-9e77-cd8c5a073849.png)

**Comment by thomasjo** [comment]
This needs to be addressed in whatever language package you are using for Flow support. Syntax themes are not tied to language grammars.

Please re-open this issue in the correct package repository :bow:
