### ISSUE TITLE
Link within a comment not well coloured

### ISSUE THREAD

**Issue by gaspoute** [atom/one-dark-syntax#57]
Hi,

I observed in the last commit that a link within a comment isn't well coloured.

<img width="458" alt="commentlink" src="https://cloud.githubusercontent.com/assets/7072716/12126363/1102b082-b3f1-11e5-82d9-69edcd9749f1.png">

Gaspar

**Comment by 50Wliu** [comment]
@gaspoute what language is this?  Javascript?

**Comment by gaspoute** [comment]
Yep Javascript.

**Comment by 50Wliu** [comment]
Ok, it looks like this syntax theme is applying link styling after comments.  Not sure if that's intended or not.

**Comment by simurai** [comment]
Probably not intended, but maybe useful only in documentation blocks at the beginning?

![screen shot 2016-01-07 at 12 12 33 am](https://cloud.githubusercontent.com/assets/378023/12145781/8dcbe560-b4d3-11e5-8285-58fdf5808a28.png)

**Comment by gaspoute** [comment]
Yep, it's a good idea.

**Comment by simurai** [comment]
On the other hand.. having it purple for documentation comments, it might look like you can click it.

We could also just keep it grey, but a tiny bit brighter. Like this:

![screen shot 2016-01-07 at 11 00 55 am](https://cloud.githubusercontent.com/assets/378023/12160312/16bae5ec-b52e-11e5-99d2-365ee5fa639c.png)

Then it still sticks out a bit, but not too much.

**Comment by djch** [comment]
I'm always partial to underlining links/URLs. I don't think it's used for anything else in this syntax theme, so maybe that'd help stand them out without needing to adjust the colours as much?

**Comment by simurai** [comment]
![screen shot 2016-01-07 at 11 21 48 am](https://cloud.githubusercontent.com/assets/378023/12160601/ee022482-b530-11e5-8313-7d76a156c5cf.png)

@djch Ya, that would keep them consistent. Ok, let's do that. :+1:
