### ISSUE TITLE
Github code block formatting

### ISSUE THREAD

**Issue by tillkruss** [atom/one-dark-syntax#65]
Standard code blocks are highlighted in green. 

    ```
    $foo = new Foobar;
    ```

But code blocks with their language specified don't have any highlighting at all.

    ```php
    $foo = new Foobar;
    ```

**Comment by simurai** [comment]
@tillkruss Sorry for the late reply. For now you could add the following to your `styles.less` file:

```css
atom-text-editor::shadow .markup.gfm .embedded.php {
  color: hsl( 95, 38%, 62%);
}
```

That should make PHP code blocks green too:

![screen shot 2016-06-14 at 3 59 56 pm](https://cloud.githubusercontent.com/assets/378023/16033816/2205016a-3249-11e6-8943-24259876add3.png)

We _could_ add the above to this theme, but it would be even better to open an issue in [language-php](https://github.com/atom/language-php). Then full syntax highlighting might can be added and not be treated as raw (without language) code.
