### ISSUE TITLE
How can I hack into the syntax?

### ISSUE THREAD

**Issue by webdif** [atom/one-dark-syntax#66]
I want to test some change in the styles of my local Atom, but I can't find where one-dark-syntax package is. My goal is to add support for pug (jade) syntax.

Can you help me?

**Comment by 50Wliu** [comment]
`apm develop https://github.com/atom/one-dark-syntax` --> should place `one-dark-syntax` in `~/github`.
`atom --dev` to load the local version.

If that doesn't work you can clone this repository and then `apm link` it.
