### ISSUE TITLE
es2015 `from` highlighting

### ISSUE THREAD

**Issue by amk221** [atom/one-dark-syntax#68]
_from_ is being highlighted correctly like so:
<img width="182" alt="screen shot 2016-06-02 at 15 26 35" src="https://cloud.githubusercontent.com/assets/382061/15748347/6f1dc4ae-28d6-11e6-812d-51d5aafeba40.png">
but incorrectly when used elsewhere, afaik it's not a reserved word?
<img width="491" alt="screen shot 2016-06-02 at 15 21 46" src="https://cloud.githubusercontent.com/assets/382061/15748229/e9a74df4-28d5-11e6-8959-7eb7fc80abef.png">

Unsure if this is a one-dark-syntax issue or a greater atom issue, so sorry if this is in the wrong place

**Comment by 50Wliu** [comment]
@amk221 Please report this to the [atom/language-javascript](https://github.com/atom/language-javascript) repository.  Thanks!
