### ISSUE TITLE
Text is supposed to be light gray but is blue

### ISSUE THREAD

**Issue by smlombardi** [atom/one-dark-syntax#7]
Poking around the files I see s syntax-text-color variable is light gray.

However, in an HTML file, my text is light blue, same as the tag punctuation:

![screen shot 2015-01-23 at 9 22 06 am](https://cloud.githubusercontent.com/assets/835148/5876011/83108fd6-a2e1-11e4-8a49-3fbc76bff2d8.png)

**Comment by stramel** [comment]
Everything seems to have a slight bluish-tint to it when this theme is applied.

**Comment by lombardi-gux** [comment]
True.  I think making plain text a neutral color (some sort of gray or off-white) would improve readability.

**Comment by simurai** [comment]
@stramel Yes, there is some blue-ish tinting to match the background color. Initially the plan was to add some options to the settings so you could change things like hue, saturation, lightness. But that had to be put on ice for the moment.

So yeah.. for now, let's reduce the tinting and increasing the contrast a bit. I think in the end, it always depends on the environment that you're in. Dark room vs coffee shop with sunlight.

**Comment by smlombardi** [comment]
>Dark room vs coffee shop with sunlight.

Split the difference, and use an office cubicle with lots of fluorescent lighting...

**Comment by simurai** [comment]
ok.. started a new branch. Will tinker a bit with the colors.

One day we'll get `light-level` Media Queries and then it could adapt to the environment automatically.

**Comment by stramel** [comment]
> One day we'll get light-level Media Queries and then it could adapt to the environment automatically.

Wouldn't that be awesome? I was working on doing similar stuff for house lighting. I hadn't thought about computers.

**Comment by braver** [comment]
Until that day: https://justgetflux.com ;) Seriously though, light levels are a huge reason for me to switch between light and dark themes, and I'd love some choice in between.

**Comment by stramel** [comment]
Yeah, I use flux on my home pcs

**Comment by simurai** [comment]
Heh.. yep, I used flux a while back and probably still would but I found myself temp disabling it way too often to see the "real" colors.

Something I'm not sure with `light-levels`. Should a theme completely switch from dark to light or just adjust the contrast a bit. I'm thinking automatically switching could be annoying and will throw you off.

**Comment by lombardi-gux** [comment]
I would hate to have a theme, or any UI self adjust. I've disabled things like auto brightness on my Mac and iPhone.


On Feb 23, 2015, at 10:22 PM, simurai <notifications@github.com<mailto:notifications@github.com>> wrote:


Heh.. yep, I used flux a while back and probably still would but I found myself temp disabling it way too often to see the "real" colors.

Something I'm not sure with light-levels. Should a theme completely switch from dark to light or just adjust the contrast a bit. I'm thinking automatically switching could be annoying and will throw you off.

—
Reply to this email directly or view it on GitHub<https://github.com/atom/one-dark-syntax/issues/7#issuecomment-75691795>.

________________________________

**Comment by simurai** [comment]
In my case, I really like that for example Instapaper switches automatically to light text on a dark background when it gets dark, like at night. Easier to read and less jarring. But that's just when reading text. Having syntax highlighting automatically change is probably a different story.

**Comment by braver** [comment]
iBooks also does that flip to negative and it works well enough to leave it on. Just be sure not to put anything in front of the sensor.
For code though I think you would need a syntax theme like Solarized, that maintains the colouring and overall contrast, but flip the base back and foreground color. Transitioning between dark and light is though, how do you deal with contrast?

There is already [this](https://atom.io/packages/theme-toggler) and [this](https://atom.io/packages/theme-switcher) that enable manual 'flipping'. And apparently [this](https://github.com/mattapperson/outdoor-theme) theme that does it automatically based on a mac's light sensor (altough I kinda doubt that one still works).

**Comment by simurai** [comment]
Just tested Outdoor theme and it works for me when turning on/off my room lamp. But only if I change the "Light Level to Switch" to `500000`. Probably it needs to be calibrated.

Anyways.. I'll try it for a few days and see how it feels.

**Comment by stramel** [comment]
@smlombardi Was this resolved?

**Comment by smlombardi** [comment]
i can't tell, really.  The conversation digressed.  Any other status
reports?

**Comment by simurai** [comment]
Sorry, not yet. I started a `sm-neutralize` branch, but it hasn't been merged into master.

I'll reopen this again.

**Comment by simurai** [comment]
Text color is now less blue:

Before:
![screen shot 2015-03-18 at 5 54 14 am](https://cloud.githubusercontent.com/assets/378023/6697529/713453ec-cd34-11e4-8e77-a4700fa7ecec.png)

After:
![screen shot 2015-03-18 at 5 53 43 am](https://cloud.githubusercontent.com/assets/378023/6697533/76682f28-cd34-11e4-85d3-592d7763078b.png)

**Comment by smlombardi** [comment]
Does this show up in the next Atom release, or do we need to install this package as well?

**Comment by simurai** [comment]
You don't need to manually update. It will be part of one of the upcoming Atom releases.
