### ISSUE TITLE
Comments move text below

### ISSUE THREAD

**Issue by wemyss** [atom/one-dark-syntax#72]
I noticed that using this theme (and a few others such as Firewatch and Gruvbox) that the comments shift text on code lines below such that it pushes them almost onto other lines like so:
<img width="188" alt="screen shot 2016-08-10 at 9 40 17 pm" src="https://cloud.githubusercontent.com/assets/8426915/17552396/251368ca-5f43-11e6-8ddd-f300b1701429.png">

Using the `atom dark` syntax theme rather than `one dark` syntax fixes this however.

Not sure what causes this or if it is intended. :)

**Comment by simurai** [comment]
I can't reproduce this. Have you tried starting Atom in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by wemyss** [comment]
Hmmm the issue is still present in safe mode. Using `hack` font-family with `one-dark-syntax` makes this issue it seems for me (if I use the default font family the bug does not occur). 

Also to note, while using `hack` there is no issue with `atom dark`. Not sure if this is an issue with the font or with syntax?

**Comment by mmcbride1007** [comment]
For what it's worth, I've noticed this as well and I also use Hack. Never thought about it being a font issue, but maybe that's the culprit?

**Comment by simurai** [comment]
Tried it with the latest version of Hack: https://github.com/chrissimpkins/Hack. But still can't reproduce it. In case you downloaded it a while ago, maybe worth to try an updated version?

Also, a difference between `One dark` and `Atom dark` is that One dark [uses _italic_ for comments](https://github.com/atom/one-dark-syntax/blob/master/styles/language.less#L5). So maybe if you haven't installed the _italic_ version of Hack, it tries to do it in software which might messes up something with the height? You could try to disable the _italic_ for comments with:

```css
atom-text-editor::shadow .comment {
  font-style: normal;
}
```

**Comment by mmcbride1007** [comment]
I also spent some time this morning trying to reproduce it and it seems I can't get it to happen anymore either. It was a while ago that I saw this...

**Comment by wemyss** [comment]
With the new version of Hack the issue seems to have disappeared. Thanks for the help everyone.
