### ISSUE TITLE
Syntax highlight issue

### ISSUE THREAD

**Issue by sleewoo** [atom/one-dark-syntax#73]
Hi,
not a big issue but occasionally annoying as it make me feel my code is wrong :)

![output](https://cloud.githubusercontent.com/assets/9264860/18156945/e2851d8c-7022-11e6-9412-50882a863234.gif)

It happens on any syntax theme and not only with `constructor` keyword.
Thank you.

**Comment by sleewoo** [comment]
Atom Version 1.10.0

**Comment by sleewoo** [comment]
OS X El Capitan 10.11.6

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/language-javascript](https://github.com/atom/language-javascript) package.

**Comment by sleewoo** [comment]
thanks
