### ISSUE TITLE
"DISTINCT" in SQL is not highlighted

### ISSUE THREAD

**Issue by bherman-fontys** [atom/one-dark-syntax#75]
As the title says, the word "DISTINCT" in SQL doesn't seem to be highlighted - and it's a quite important keyword in my opinion.

**Comment by timwangdev** [comment]
You may need to report this issue to https://github.com/atom/language-sql

**Comment by 50Wliu** [comment]
Whoops, thanks for catching this @timwangdev!  Totally thought I was already in language-sql.
