### ISSUE TITLE
improve json highlighting

### ISSUE THREAD

**Issue by gosteev** [atom/one-dark-syntax#76]
hello. i work with large json files periodically, and noticed something that i miss in 'one dark syntax' theme.
sublime material theme has next json highlighting:

![image](https://cloud.githubusercontent.com/assets/6203574/18815789/b2b540d6-8342-11e6-803b-3c26041c19e7.png)

this is the same chunk, but in atom with one dark syntax:

![image](https://cloud.githubusercontent.com/assets/6203574/18815801/ef014be8-8342-11e6-8c88-382bc5046ae2.png)

keys of keys has more saturated red color, and 'root' keys are purple at all.
it is not critical, but significantly improves understanding of structure, especially when you are tired.

also - maybe there is a reason to make color of quotes a bit darker, so user could focus more on keys / values, not quotes ([example](https://cloud.githubusercontent.com/assets/6203574/17449614/77fd6550-5b64-11e6-8a79-aae36d5fa3ee.png))

**Comment by occurr** [comment]
I know this is a year old, but it can be done. 

If `Show Indentation Guide` is turned on there is one `<span class=leading-whitespace indent-guide>` per tab.  As long as `Show Indentation Guide` is enabled, using `nth-child` works. 

I will create a pull request to add this support soon.

**Comment by simurai** [comment]
There is now a PR that adds up to 6 indentation levels: https://github.com/atom/one-dark-syntax/pull/113

I'm still a bit on the edge about it. On the one hand, it can help with indentation, on the other hand, it's harder to see what is a key and what a value because keys can have different colors. Hmmm.. 🤔

**Comment by Aerijo** [comment]
@simurai I think the change would be very confusing, especially to current users of this theme (I was taken aback when I saw the PR just now). 

It would be ideal to have a setting somewhere, but that may be difficult to do cleanly. Alternatively, the colour change could be more subdued, like in the Sublime screenshot. Even then, there will be a few people rasing issues and asking questions about how the theme broke...

**Comment by simurai** [comment]
Yeah, agreed. I think it a bit too much. For now, let's close this as `wontfix`.
