### ISSUE TITLE
and, or, ... keywords not highlighted

### ISSUE THREAD

**Issue by jhasse** [atom/one-dark-syntax#77]
![bildschirmfoto vom 2016-08-15 16-33-10](https://cloud.githubusercontent.com/assets/80071/17667638/fb5ad754-6305-11e6-9838-b1cf4e85279e.png)

Expected:
```cpp
int main() {
    if (a or b and c || d && e) {
    }
}
```

See https://github.com/atom/language-c/issues/157

**Comment by simurai** [comment]
This will be fixed in Atom `1.12`.
