### ISSUE TITLE
Latest Atom Breaks One Dark Syntax

### ISSUE THREAD

**Issue by jonobr1** [atom/one-dark-syntax#84]
I updated to the latest atom today (1.12.6) and the syntax highlighting for One Dark disappeared..!

<img width="1183" alt="screen shot 2016-12-07 at 11 51 12 am" src="https://cloud.githubusercontent.com/assets/220033/20984011/7a309912-bc73-11e6-8beb-5e3f5531d12c.png">

Because the theme is pre-bundled with atom I couldn't uninstall / reinstall or disable / enable the theme. I tried restarting atom and restarting my computer but no go. One Dark UI seems to be fine. When I download new themes they seem to work fine. On OSX El Capitan 10.11.6 iMac.

**Comment by 50Wliu** [comment]
Please uninstall one-dark-syntax: `apm uninstall one-dark-syntax`.  Atom will then properly use the bundled one.

**Comment by jonobr1** [comment]
That did it! Thanks!
