### ISSUE TITLE
Markdown Syntax coloring (links vs. emphasis)

### ISSUE THREAD

**Issue by bobrocke** [atom/one-dark-syntax#87]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The color coding for emphasized text in Markdown files uses the same color as for links.

![2016-12-28 at 7 22 am](https://cloud.githubusercontent.com/assets/2962426/21521848/862bda36-ccce-11e6-9129-61c5d1dbdc8a.jpg)

I'd like for them to be different.

**Comment by simurai** [comment]
How about **cyan**? It's still unused within [markup](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax/_base.less#L266-L308).

Made a PR here: https://github.com/atom/one-dark-syntax/pull/88
