### ISSUE TITLE
Syntax color is mismatch for this PHP source (1.18.0)

### ISSUE THREAD

**Issue by Daijobou** [atom/one-dark-syntax#97]
Atom : 1.18.0
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0

See this mismatch syntax color in image
![grafik](https://user-images.githubusercontent.com/260343/27997047-d1b7b344-64ef-11e7-9cfa-e7f79d61beff.png)

In this version I remove only the empty comment line and its fine
![grafik](https://user-images.githubusercontent.com/260343/27997055-18095b72-64f0-11e7-9029-ed5ac08e364e.png)

Here with empty comment line and I remove instead in SQL code "a" (red rectangle)
![grafik](https://user-images.githubusercontent.com/260343/27997067-76e878ee-64f0-11e7-86a8-8068f96207e5.png)

What happen here? Here the code for testing
`<?php
// 
$select = DB::query('SELECT * FROM table a INNER JOIN table2 b ON a.fieldA=b.fieldA WHERE a.fieldB>:var1 AND a.fieldC=:var2 AND a.fieldD IN (1,2) AND NOT EXISTS (SELECT * FROM table3 c WHERE c.fieldA=:var3 AND c.fieldB=a.fieldC AND c.fieldC IN (1,2,6) LIMIT 1)')
->bind(':var1', $var1)
->bind(':var2', $var2)
->bind(':var3', $var3);

$value1 = 1;
$value2 = 'text';`

P.S. That issue is with all themes installed in atom. I'm not sure where report this issue :)

**Comment by timwangdev** [comment]
https://github.com/atom/language-php/issues Here please.
